version: "3.7"
services:
  ui:
    image: picoctf/ui
    build:
      context: ui
    container_name: pico_ui
    ports:
      - target: 443
        published: 13371
        protocol: tcp
        mode: host
    depends_on:
      - api
  api:
    image: picoctf/api
    build:
      context: api
    container_name: pico_api
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:4.2-bionic
    container_name: pico_mongo
  redis:
    image: redis:5
    container_name: pico_redis
