version: "3.7"
services:
  ui:
    image: picoctf/ui
    build:
      context: ui
    container_name: pico_ui
    ports:
      - target: 443
        published: 13371
        protocol: tcp
        mode: host
    depends_on:
      - api
  api:
    image: picoctf/api
    build:
      context: api
    container_name: pico_api
    depends_on:
      - mongo
      - redis
  cache-daemon:
    image: picoctf/api
    build:
      context: api
    container_name: pico_cache_daemon
    depends_on:
      - mongo
      - redis
      - api
    entrypoint:
      - python
      - -u
      - /app/cache_daemon.py
  mongo:
    image: mongo:4.2-bionic
    container_name: pico_mongo
  redis:
    image: redis:5
    container_name: pico_redis
