version: "3.7"
services:
  ui:
    image: picoctf/ui
    build:
      context: ui
    container_name: pico_ui
    ports:
      - target: 443
        published: 13371
        protocol: tcp
        mode: host
    depends_on:
      - api
      - webshell-dispatch
  api:
    image: picoctf/api
    build:
      context: api
    container_name: pico_api
    depends_on:
      - mongo
      - redis
  cache-daemon:
    image: picoctf/api
    build:
      context: api
    container_name: pico_cache_daemon
    depends_on:
      - mongo
      - redis
      - api
    entrypoint:
      - python
      - -u
      - /app/cache_daemon.py
  mongo:
    image: mongo:4.2-bionic
    container_name: pico_mongo
  redis:
    image: redis:5
    container_name: pico_redis
  webshell-dispatch:
    image: picoctf/webshell-dispatch
    build:
      context: webshell
      dockerfile: dispatcher.Dockerfile
    container_name: pico_webshell_dispatch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - webshell-toolbox
  webshell-toolbox:
    # Not used, but included so that the toolbox image is built.
    # See https://github.com/docker/compose/issues/1896
    image: picoctf/toolbox
    build:
      context: webshell
      dockerfile: toolbox.Dockerfile
