---
# Playbook that configures nginx on picoCTF-shell

- name: Add picoCTF site configuration to nginx
  template:
    src: shell.nginx.j2
    dest: "/etc/nginx/sites-available/{{ shell_site_config_name }}"
    backup: yes
    owner: root
    group: root
    mode: 0644

- name: Enable picoCTF-shell site configuration
  file:
    src: "/etc/nginx/sites-available/{{ shell_site_config_name }}"
    dest: "/etc/nginx/sites-enabled/{{ shell_site_config_name }}"
    owner: root
    group: root
    state: link
  notify :
    - nginx restart

- name: Disable default nginx site configuration
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

# Install SSL cert and key for nginx
- name: Copy SSL cert
  copy:
    src: ssl-pico.chained.crt
    dest: /etc/ssl/certs/ssl-pico.chained.crt
    owner: root
    group: root
    mode: 0644
  when: enable_shell_ssl | bool

- name: Copy SSL key
  copy:
    src: ssl-pico.key.vault_encrypted
    dest: /etc/ssl/private/ssl-pico.key
    owner: root
    group: root
    mode: 0644
  when: enable_shell_ssl | bool

