---
# Playbook that installs and configures services on the shell_server

- name: Copy over limits.conf
  copy:
    src: limits.conf
    dest: /etc/security/limits.conf
    owner: root
    group: root
    mode: 0644

- name: Copy over sysctl.conf
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 0644

- name: Reload sysctl
  command: sysctl --system

- name: Restart networking service to pickup new configs
  command: systemctl restart systemd-networkd

- name: Copy over journald.conf
  copy:
    src: journald.conf
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: 0644

- name: Restart systemd-journald service to pickup new configs
  service:
    name: systemd-journald
    state: restarted

- name: Add problems group
  group:
    name: problems
    state: present

- name: Copy over login.defs
  copy:
    src: login.defs
    dest: /etc/login.defs
    owner: root
    group: root
    mode: 0644

- name: Disable systemd.logind permenantly by masking
  systemd:
    name: systemd-logind.service
    state: stopped
    masked: yes

# REJECT would be more helpful to anyone trying. So DROP it.
- name: Add iptables rules and save them
  block:
    - name: Block outgoing SMTP
      iptables:
        chain: OUTPUT
        destination_port: smtp
        protocol: tcp
        jump: DROP
      register: block_smtp
    - name: Save iptables rules
      command: netfilter-persistent save
      when: block_smtp is changed


- name: Install tc-limit service
  block:
    - name: Add tc-limit.service
      template:
        src: tc-limit.service.j2
        dest: "/etc/systemd/system/tc-limit.service"
        owner: root
        group: root
        mode: 0644
    - name: Get systemd to pickup tc-limit.service
      command: systemctl daemon-reload
    - name: Remove tc rules if they already exist, ignore error if they don't
      command: "tc qdisc del dev {{ ansible_default_ipv4.interface }} handle 1: root htb default 11"
      ignore_errors: True
    - name: Ensure limit-tc is enabled and started
      service:
        name: tc-limit.service
        state: started
        enabled: yes
  when: on_aws | default(False) | bool
