---
# Playbook that installs and configures the picoCTF shell_manager from source

# Fix "Invalid environment marker: platform_python_implementation != 'PyPy'"
- name: Upgrade setuptools
  pip:
    name: "setuptools"
    virtualenv: "{{ virtualenv_dir }}"
    extra_args: "--upgrade"

# Source was cloned in main
- name: Install picoCTF-shell-manager from source
  pip:
    name: "file://{{ shell_manager_dir }}/challenge-server"
    virtualenv: "{{ virtualenv_dir }}"
    extra_args: "--upgrade"

- name: Create symlink for easy sudo access
  file:
    src: "{{ virtualenv_dir }}/bin/shell_manager"
    dest: "/usr/local/bin/shell_manager"
    state: link

- name: Ensure /opt/hacksports/shared directory exists
  file:
    path: /opt/hacksports/shared
    state: directory
    owner: root
    group: root

- name: Ensure /opt/hacksports/local directory exists
  file:
    path: /opt/hacksports/local
    state: directory
    owner: root
    group: root

- name: Add shared configuration for shell_manager
  template:
    src: shared_config.json.j2
    dest: "/opt/hacksports/shared/shared_config.json"
    owner: root
    group: root
    mode: 0600

- name: Add local configuration for shell_manager
  template:
    src: local_config.json.j2
    dest: "/opt/hacksports/local/local_config.json"
    owner: root
    group: root
    mode: 0600

# From shell_manager  setup.py data_files
- name: Ensure extra directory exists
  file:
    path: /opt/hacksports/shared/extra
    state: directory
    owner: root
    group: root

- name: Copy no_aslr_wrapper.c to deployed location
  copy:
    src:  "no_aslr_wrapper.c"
    dest: "/opt/hacksports/shared/extra/"

- name: Ensure config directory exists
  file:
    path: /opt/hacksports/shared/config
    state: directory
    owner: root
    group: root

- name: Ensure debs directory exists
  file:
    path: /opt/hacksports/shared/debs
    state: directory
    owner: root
    group: root
