"""
Default Flask app startup settings.

Overridable by voluming in a customized /app/config/custom_settings.py
"""

MONGO_HOST = "mongo"
MONGO_PORT = 27017
MONGO_DB_NAME = "picoCTF"
MONGO_USERNAME = None
MONGO_PASSWORD = None
MONGO_USE_SSL = False
MONGO_SSL_CACERTS = None
MONGO_REPLICASET = None
MONGO_READPREFERENCE = "primary"

REDIS_DB_NUMBER = 0
REDIS_ADDR = "redis"
REDIS_PORT = 6379
REDIS_PW = None

RATE_LIMIT_BYPASS_KEY = "INSECURE_DEFAULT_CHANGE_ME"
SECRET_KEY = "INSECURE_DEFAULT_CHANGE_ME"

SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_PATH = "/"
SESSION_COOKIE_NAME = "flask"
